"""Initial migration

Revision ID: 0c4301689679
Revises: 
Create Date: 2025-10-13 11:02:33.792417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0c4301689679'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('is_bot', sa.Boolean(), nullable=False),
                    sa.Column('first_name', sa.String(length=255), nullable=False),
                    sa.Column('count_views_movies', sa.BigInteger(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_bot'), 'users', ['is_bot'], unique=False)

    op.create_table('playlists',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_playlists_id'), 'playlists', ['id'], unique=False)
    op.create_index(op.f('ix_playlists_is_deleted'), 'playlists', ['is_deleted'], unique=False)

    op.create_table('movies',
                    sa.Column('internal_id', sa.UUID(), nullable=False),
                    sa.Column('manual_title', sa.String(length=255), nullable=False),
                    sa.Column('manual_rating', sa.Float(), nullable=False),
                    sa.Column('omdb_genres', sa.ARRAY(
                        sa.Enum('ACTION', 'ADVENTURE', 'ANIMATION', 'Biography', 'COMEDY', 'CRIME', 'DOCUMENTARY',
                                'DRAMA', 'FAMILY', 'FANTASY', 'HISTORY', 'HORROR', 'MUSIC', 'MUSICAL', 'MYSTERY',
                                'ROMANCE', 'SPORT', 'THRILLER', 'WAR', 'WESTERN', 'NEWS', 'SHORT', 'SCIFI', 'GAMESHOW',
                                'REALITYTV', 'TALKSHOW', name='genreoffilmenum')), nullable=False),
                    sa.Column('imdb_rating', sa.Float(), nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('playlist_id', sa.UUID(), nullable=False),
                    sa.Column('is_viewed', sa.Boolean(), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('internal_id')
                    )
    op.create_index(op.f('ix_movies_internal_id'), 'movies', ['internal_id'], unique=False)
    op.create_index(op.f('ix_movies_is_deleted'), 'movies', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_is_deleted'), table_name='movies')
    op.drop_index(op.f('ix_movies_internal_id'), table_name='movies')
    op.drop_table('movies')
    op.drop_index(op.f('ix_playlists_is_deleted'), table_name='playlists')
    op.drop_index(op.f('ix_playlists_id'), table_name='playlists')
    op.drop_table('playlists')
    op.drop_index(op.f('ix_users_is_bot'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
